imports:
    - { resource: config.yml }

framework:
    validation:
        cache: apc

doctrine:
    orm:
        auto_mapping: true
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

services:
    monolog.formatter.htmlformatter:
        class: Monolog\Formatter\HtmlFormatter
    monolog.processor.gitprocessor:
        class: Monolog\Processor\GitProcessor
        tags:
            - { name: monolog.processor }

monolog:
    handlers:
        main:
            type:               fingers_crossed
            action_level:       error
            handler:            grouped
        grouped:
            type:               group
            members:            [streamed, swift]
        streamed:
            type:               stream
            path:               "%kernel.logs_dir%/%kernel.environment%.log"
            level:              debug
        swift:
            type:               swift_mailer
            from_email:         %monolog_from%
            to_email:           %monolog_to%
            subject:            "NantarenaWebsite Error"
            level:              error
            content_type:       text/html
            formatter:          monolog.formatter.htmlformatter
        login:
            type:               stream
            path:               "%kernel.logs_dir%/auth.log"
            level:              info
            channels:           security
