# Montage du SiteBundle en mode annotation
nantarena_site:
    resource: "@NantarenaSiteBundle/Controller/"
    type:     annotation
    prefix:   /

# Routes vers le login
login:
    pattern:   /login
    defaults:  { _controller: NantarenaSiteBundle:Security:login }
login_check:
    pattern:   /login_check
logout:
    pattern:   /logout

# Décommentez les lignes suivantes pour activer le controleur du CoreBundle
#nantarena_core:
#    resource: "@NantarenaCoreBundle/Controller/"
#    type:     annotation
#    prefix:   /core

