security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:         ^/
            form_login:
                provider:    fos_userbundle
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                remember_me: true
                csrf_provider:  form.csrf_provider
            remember_me:
                key:         %secret%
                lifetime:    3600
                path:        /
            logout:
                path:        fos_user_security_logout
                target:      /
            anonymous:       true
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }

