security:
    acl:
        connection: default

    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN

            - ROLE_STATIC_ADMIN

            - ROLE_FORUM_ADMIN
            - ROLE_FORUM_MODERATE

            - ROLE_NEWS_ADMIN_NEWS

            - ROLE_USER_ADMIN_USERS
            - ROLE_USER_ADMIN_GROUPS

            - ROLE_BANNER_ADMIN_HEADERNEWS
            - ROLE_BANNER_ADMIN_SPONSOR_SLIDE

            - ROLE_CONTACT_ADMIN_CATEGORY

            - ROLE_EVENT_ADMIN_EVENTS
            - ROLE_EVENT_ADMIN_ENTRIES
            - ROLE_EVENT_TOURNAMENTS_MANAGER

            - ROLE_PAYMENT_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:         ^/
            form_login:
                provider:    fos_userbundle
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                remember_me: true
                csrf_provider:  form.csrf_provider
            remember_me:
                key:         %secret%
                lifetime:    1296000
                path:        /
            logout:
                path:        fos_user_security_logout
                target:      /
            anonymous:       true
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }

    access_control:
        - { path: ^/news/comment, roles: ROLE_USER }

        - { path: ^/forum/unreads, roles: ROLE_USER }
        - { path: ^/forum/.*/reply, roles: ROLE_USER }
        - { path: ^/forum/.*/create, roles: ROLE_USER }

        - { path: ^/profile, roles: ROLE_USER }

        - { path: ^/payment, roles: ROLE_USER }

        - { path: ^/admin/forum, roles: ROLE_FORUM_ADMIN }

        - { path: ^/admin/static, roles: ROLE_STATIC_ADMIN }

        - { path: ^/admin/news, roles: ROLE_NEWS_ADMIN_NEWS }

        - { path: ^/admin/users, roles: ROLE_USER_ADMIN_USERS }
        - { path: ^/admin/groups, roles: ROLE_USER_ADMIN_GROUPS }

        - { path: ^/admin/header-news, roles: ROLE_BANNER_ADMIN_HEADERNEWS }
        - { path: ^/admin/sponsor, roles: ROLE_BANNER_ADMIN_SPONSOR_SLIDE }

        - { path: ^/admin/contact/category, roles: ROLE_CONTACT_ADMIN_CATEGORY }

        - { path: ^/admin/event/events, roles: ROLE_EVENT_ADMIN_EVENTS }
        - { path: ^/admin/event/games, roles: ROLE_EVENT_ADMIN_EVENTS }
        - { path: ^/admin/event/entries, roles: ROLE_EVENT_ADMIN_ENTRIES }
        - { path: ^/admin/event/teams, roles: ROLE_EVENT_ADMIN_ENTRIES }

        - { path: ^/admin/payment, roles: ROLE_PAYMENT_ADMIN }

        - { path: ^/admin, roles: ROLE_ADMIN } # Attention à le laisser en dernier
