security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_SUPER_ADMIN:
            - ROLE_ADMIN
            - ROLE_USER_ADMIN_USERS
            - ROLE_USER_ADMIN_GROUPS

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern:         ^/
            form_login:
                provider:    fos_userbundle
                login_path:  fos_user_security_login
                check_path:  fos_user_security_check
                remember_me: true
                csrf_provider:  form.csrf_provider
            remember_me:
                key:         %secret%
                lifetime:    3600
                path:        /
            logout:
                path:        fos_user_security_logout
                target:      /
            anonymous:       true
            switch_user: { role: ROLE_ALLOWED_TO_SWITCH }

    access_control:
        - { path: ^/news/comment, roles: ROLE_USER }

        - { path: ^/admin/users, roles: ROLE_USER_ADMIN_USERS }
        - { path: ^/admin/groups, roles: ROLE_USER_ADMIN_GROUPS }

        - { path: ^/admin, roles: ROLE_ADMIN } # Attention à le laisser en dernier
