security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      default_provider:
        memory:
          users:
            user:  { password: userpass, roles: [ 'ROLE_USER' ] }
            admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
            superadmin: { password: superadminpass, roles: [ 'ROLE_SUPER_ADMIN' ] }
        #entity:
          # entité User a renseigner ici

    firewalls:
      dev:
          pattern:  ^/(_(profiler|wdt)|css|images|js)/
          security: false
      secured_area:
          pattern:    ^/
          anonymous:  ~
          form_login: ~
          logout:     ~
          # switch d'user à la volée
          switch_user: { role: ROLE_ALLOWED_TO_SWITCH }

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/logout, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
