parameters:
    # news bundle parameters

services:
    nantarena_news.admin_event:
        class: Nantarena\NewsBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard }

    nantarena_news.news_manager:
        class: Nantarena\NewsBundle\Manager\NewsManager
        arguments: [@router]

    nantarena_news.category_manager:
        class: Nantarena\NewsBundle\Manager\CategoryManager
        arguments: [@router]

    nantarena_news.comment_manager:
        class: Nantarena\NewsBundle\Manager\CommentManager
        arguments: [@router]

    nantarena_news.twig.news_extension:
        class: Nantarena\NewsBundle\Twig\NewsExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setNewsManager, [@nantarena_news.news_manager] ]
            - [ setTranslator, [@translator] ]

    nantarena_news.twig.comment_extension:
        class: Nantarena\NewsBundle\Twig\CommentExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setCommentManager, [@nantarena_news.comment_manager] ]

    nantarena_news.twig.category_extension:
        class: Nantarena\NewsBundle\Twig\CategoryExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setCategoryManager, [@nantarena_news.category_manager] ]
