services:
    nantarena_event.admin_event:
        class: Nantarena\EventBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard}

    nantarena_event.user_entry_constraint:
        class: Nantarena\EventBundle\Validator\Constraints\UserEntryConstraintValidator
        arguments: [@doctrine.orm.entity_manager, @translator]
        tags:
            - { name: validator.constraint_validator, alias: user_entry_constraint }

    nantarena_event.team_name_constraint:
        class: Nantarena\EventBundle\Validator\Constraints\TeamNameConstraintValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: team_name_constraint }

    nantarena_event.team_tag_constraint:
        class: Nantarena\EventBundle\Validator\Constraints\TeamTagConstraintValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: team_tag_constraint }

    nantarena_event.team_members_tournaments_constraint:
        class: Nantarena\EventBundle\Validator\Constraints\TeamMembersTournamentsConstraintValidator
        arguments: [@doctrine.orm.entity_manager]
        tags:
            - { name: validator.constraint_validator, alias: team_members_tournaments_constraint }
