parameters:

services:
    # Managers
    nantarena_forum.category_manager:
        class: Nantarena\ForumBundle\Manager\CategoryManager
        arguments: [@router]

    nantarena_forum.forum_manager:
        class: Nantarena\ForumBundle\Manager\ForumManager
        arguments: [@router]

    nantarena_forum.thread_manager:
        class: Nantarena\ForumBundle\Manager\ThreadManager
        arguments: [@router]

    # Extensions twig
    nantarena_forum.twig.category_extension:
        class: Nantarena\ForumBundle\Twig\CategoryExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]

    nantarena_forum.twig.forum_extension:
        class: Nantarena\ForumBundle\Twig\ForumExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]

    nantarena_forum.twig.thread_extension:
        class: Nantarena\ForumBundle\Twig\ThreadExtension
        tags:
            - { name: twig.extension }
        calls:
            - [ setContainer, [@service_container] ]