services:
    nantarena_site.db_prefix:
        class: Nantarena\SiteBundle\EventListener\TablePrefixSubscriber
        arguments: [%nantarena_site.db_prefix%]
        tags:
            - { name: doctrine.event_subscriber }

    nantarena_site.breadcrumb:
        class: Nantarena\SiteBundle\Navigation\Breadcrumb

    nantarena_site.twig.site_extension:
        class: Nantarena\SiteBundle\Twig\SiteExtension
        tags:
            - { name: twig.extension }

    nantarena_site.twig.form_extension:
        class: Nantarena\SiteBundle\Twig\FormExtension
        tags:
            - { name: twig.extension }

    nantarena_site.twig.image_extension:
        class: Nantarena\SiteBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }

    nantarena_site.twig.collection_extension:
        class: Nantarena\SiteBundle\Twig\CollectionExtension
        tags:
            - { name: twig.extension }

    nantarena_site.type.wysiwyg:
        class: Nantarena\SiteBundle\Form\Type\WysiwygType
        tags:
            - { name: form.type, alias: wysiwyg_area }

    nantarena_site.twig.breadcrumb_extension:
        class: Nantarena\SiteBundle\Twig\BreadcrumbExtension
        arguments: [@nantarena_site.breadcrumb]
        tags:
            - { name: twig.extension }


    nantarena_site.countdown.registration:
            class: Nantarena\SiteBundle\Countdown\CountdownRegistration

    nantarena_site.countdown.listener:
            class: Nantarena\SiteBundle\Countdown\CountdownListener
            arguments: [@nantarena_site.countdown.registration,"2014-10-01"]
            tags:
                - { name: kernel.event_listener, event: kernel.response, method: processCountdown }
