services:
    nantarena_site.db_prefix:
        class: Nantarena\SiteBundle\Services\TablePrefixSubscriber
        arguments: [%nantarena_site.db_prefix%]
        tags:
            - {name: doctrine.event_subscriber}

    nantarena_site.twig.form_extension:
        class: Nantarena\SiteBundle\Twig\FormExtension
        tags:
            - { name: twig.extension }

    nantarena_site.twig.image_extension:
        class: Nantarena\SiteBundle\Twig\ImageExtension
        tags:
            - { name: twig.extension }

    nantarena_site.type.wysiwyg:
        class: Nantarena\SiteBundle\Form\Type\WysiwygType
        tags:
            - { name: form.type, alias: wysiwyg_area }
