services:
    nantarena_site.db_prefix:
        class: Nantarena\SiteBundle\Services\TablePrefixSubscriber
        arguments: [%nantarena_site.db_prefix%]
        tags:
            - {name: doctrine.event_subscriber}
