services:
    nantarena_site.db_prefix:
        class: Nantarena\SiteBundle\Services\TablePrefixSubscriber
        arguments: [%nantarena_site.db_prefix%]
        tags:
            - {name: doctrine.event_subscriber}

    nantarena_news.twig.form_extension:
        class: Nantarena\SiteBundle\Twig\FormExtension
        tags:
            - { name: twig.extension }
