parameters:

services:
    nantarena_payment.paypal_service:
        class:        Nantarena\PaymentBundle\Paypal\PaypalService
        arguments:    [""]

    nantarena_payment.payment_service:
        class:        Nantarena\PaymentBundle\Payment\PaymentService
        arguments:	  [@doctrine.orm.entity_manager]

    nantarena_payment.payment_manager:
        class: Nantarena\PaymentBundle\Manager\PaymentManager
        arguments: [@router]