parameters:
    nantarena_payment.payment_timeout: 15
    nantarena_payment.payment_delete_security_time: 1
    nantarena_payment.payment_min_euro: 0.10

services:
    nantarena_payment.paypal_service:
        class:        Nantarena\PaymentBundle\Paypal\PaypalService
        arguments:    [""]

    nantarena_payment.payment_service:
        class:        Nantarena\PaymentBundle\Payment\PaymentService
        arguments:	  [@doctrine.orm.entity_manager]

    nantarena_payment.payment_manager:
        class: Nantarena\PaymentBundle\Manager\PaymentManager
        arguments: [@router]

    nantarena_payment.admin_payment:
        class: Nantarena\PaymentBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard}