services:
    nantarena_user.registration.form_type:
        class: Nantarena\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nantarena_user_registration }
