services:
    nantarena_user.registration.form_type:
        class: Nantarena\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nantarena_user_registration }

    nantarena_user.profile_listener:
        class: Nantarena\UserBundle\EventListener\ProfileListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber}

    nantarena_user.admin_user:
        class: Nantarena\UserBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard}
