services:
    nantarena_user.registration.form_type:
        class: Nantarena\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nantarena_user_registration }

#    nantarena_user.role_filter:
#        class: Nantarena\UserBundle\Services\RoleFilter
#        arguments: [@router, @security.context]
#        tags:
#            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
