services:
    nantarena_user.registration.form_type:
        class: Nantarena\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nantarena_user_registration }

    nantarena_user.profile.form_type:
        class: Nantarena\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: nantarena_user_profile }

    nantarena_user.profile_listener:
        class: Nantarena\UserBundle\EventListener\ProfileListener
        arguments: [@router]
        tags:
            - { name: kernel.event_subscriber }

    nantarena_user.group_subscriber:
        class: Nantarena\UserBundle\EventListener\GroupSubscriber
        tags:
            - { name: doctrine.event_subscriber }

    nantarena_user.admin_user:
        class: Nantarena\UserBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard }

    nantarena_user.groups.group_type:
        class: Nantarena\UserBundle\Form\Type\GroupType
        arguments: [%security.role_hierarchy.roles%, @translator]

    nantarena_user.user_manager:
        class: Nantarena\UserBundle\Manager\UserManager
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]

    nantarena_user.group_manager:
        class: Nantarena\UserBundle\Manager\GroupManager
        arguments: [@fos_user.entity_manager, %fos_user.model.group.class%, @nantarena_user.user_manager]
