parameters:

services:
    nantarena_contact.admin_contact:
        class: Nantarena\ContactBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard}
    nantarena_contact.category_manager:
        class: Nantarena\ContactBundle\Manager\CategoryManager
        arguments: [@router]