parameters:

services:
    nantarena_banner.admin_banner:
        class: Nantarena\BannerBundle\Controller\AdminController
        tags:
            - { name: nantarena_admin.dashboard}

    nantarena_banner.header_news_manager:
        class: Nantarena\BannerBundle\Manager\HeaderNewsManager
        arguments: [@router]

    nantarena_banner.sponsor_slide_manager:
        class: Nantarena\BannerBundle\Manager\SponsorSlideManager
        arguments: [@router]
